### ISSUE TITLE
Callback testCollectionComplete is not called anymore

### ISSUE THREAD

**Issue by mlewand** [quailjs/quail#301]
It looks like `testCollectionComplete` callback is not called anymore.

## TC

Simply use any code that makes use of `testCollectionComplete` callback.

You might use [this demo](https://gist.github.com/mlewand/73d2cd4f767d4946c088). It is supposed to call an `alert` after the check is done.

## First commit

I already did a bisect, and first commit when it's broken is: 4fac493409c328526abcb03e1a7a3b5f22280598.

**Comment by jessebeach** [comment]
I think it's because of this function:

https://github.com/quailjs/quail/blob/master/src/js/core.js#L98

It's completely bit-rotted. I keep running into this as well. We should be able to simply pass in an array of assessment names a strings to have Quail run them. 

Are you passing a single assessment name as a string to Quail in the ```accessibilityTests``` property? Try wrapping the string in an array.

I know this is not ideal :/ I keep running into it as well. Maybe I should just update the ```buildTests``` function I linked to above to also accept a string for a single test. That seems like a good monkey patch for the moment.

**Comment by jessebeach** [comment]
Cannot reproduce, sorry!
